### PR TITLE
Example and Windows CI

### PR DESCRIPTION
**Pull request by tritao**

### CODE REVIEW

**Comment by ak1394** [comment]
Hi @tritao ! I've merged the latest changes, but I'm seeing the failure during the build:

- Build failed with message      1>D:\a\react-native-tts\react-native-tts\example\windows\amuseTts.sln.metaproj : error MSB3202: The project file "D:\a\react-native-tts\react-native-tts\example\windows\..\node_modules\react-native-tts\windows\RNTTS\RNTTS.vcxproj" was not found. [D:\a\react-native-tts\react-native-tts\example\windows\amuseTts.sln]. Check your build configuration.
✖ Build failed with message      1>D:\a\react-native-tts\react-native-tts\example\windows\amuseTts.sln.metaproj : error MSB3202: The project file "D:\a\react-native-tts\react-native-tts\example\windows\..\node_modules\react-native-tts\windows\RNTTS\RNTTS.vcxproj" was not found. [D:\a\react-native-tts\react-native-tts\example\windows\amuseTts.sln]. Check your build configuration.

**Comment by tritao** [comment]
I'll check it out on Monday

**Comment by tritao** [comment]
Hey @ak1394, sorry I have not looked into the CI issue yet, will be fixed ASAP.

**Comment by ak1394** [comment]
No worries @tritao thanks for looking into it!

**Comment by ak1394** [comment]
BTW is https://github.com/ak1394/react-native-tts/pull/169 anyhow related to it?

**Comment by tritao** [comment]
I think so, but there are other issues, CI is too slow and fails with the time delays specified in the tests.

@jaimecbernardo was looking into it, I will coordinate with him and either of us should be sending a PR to get it fixed.

**Comment by jaimecbernardo** [comment]
Turns out GitHub actions environment is not able to use TextToSpeech correctly. I've tested using these in the environment through the PowerShell and the object returned is empty.
```
Add-Type -AssemblyName System.speech
$speak = New-Object System.Speech.Synthesis.SpeechSynthesizer
$speak.GetInstalledVoices().VoiceInfo
```
`$speak.GetInstalledVoices()` fails because the `$speak` object is empty.  
Given that this API seems to be unusable for the GitHub actions, I've added some changes to https://github.com/ak1394/react-native-tts/pull/169 so that CI runs a simpler version of the test that just builds and verifies that the Application runs successfully.

**Comment by ak1394** [comment]
@jaimecbernardo sounds good, thanks!

**Pull request merged**
